### ISSUE TITLE
Issue with Discord Bot Xenon: unexpected error occurred 4BEYXLW5HC

### ISSUE THREAD

**Issue by FlashyTommy** [Magic-Bots/xenon.bot#2]
I am a user of the Discord bot Xenon, and I am encountering some issues that I would like to report. Here are the details:

Repeated unknown errors: The bot consistently returns unknown errors. I am unable to execute commands like “clone channel” for several hours.
Bot status: Despite appearing in the list of online users, the bot shows as offline without the green dot.
Error code: The specific error code I am receiving is: 4BEYXLW5HC.
Steps to reproduce the issue:

Log in to my Discord server.
Send the “/clone channel” command.
Receive the error with the mentioned code.
I gave to the bot Admin permission, so this is not a permission problem.
Discord Version: I am using the latest Discord version, I either tried with the web app and the mobile version, same error.

Thank you for your attention, and I hope this helps address the problem with the Xenon bot.

Best regards,
TommyFlash
![Error 4BEYXLW5HC](https://github.com/Xenon-Bot/xenon.bot/assets/166531246/640a0458-58c5-4574-879f-2d6742fba99b)

**Comment by merlinfuchs** [comment]
Hey, thanks for reporting the issue! 

Would you be able to reproduce the issue again and post a new error code here? Sadly the error codes expire after 24 hours, so I can't look into it.

Thanks! :)

**Comment by FlashyTommy** [comment]
Sure, the new error code is: 4BH8KK0IC8
Thank you in advance

**Comment by merlinfuchs** [comment]
I have looked into it and in your specific case, it fails because the channel has more than 100 permissions overwrites (channel permissions). I will check if there is a way to work around this!

The error handling could definitely be improved ...

**Comment by FlashyTommy** [comment]
Yeah you're right, for every category I use to set specific permissions of each of my 100+ roles (bot roles included) - a really unproductive way to set a server Ik.
For the error handling I agree with your opinion hahhah
Anyways, as you said, if when you'll check if there's a way to work around this you'll find a solution, could you please tell me the result?

Thank you in advance

**Comment by merlinfuchs** [comment]
I might have found a solution to the problem. Can you try again now and let me know if it works?

**Comment by FlashyTommy** [comment]
Thank you so very much, you really have no idea how grateful I am to you for helping me solve this problem🙏🏼
One last question: can you explain to me why the bot is in the online list, yes, but the green online status dot doesn't appear on it?
Thank you in advance,
TommyFlash.

**Comment by merlinfuchs** [comment]
The technical explanation is that the bot is sometimes not connected to the Discord Gateway, which would make it appear online, but can still receive commands over the HTTP interaction endpoint. Discord lets bots with an HTTP interaction endpoint configured appear in the online member list.
The non-technical explanation is: It doesn't have to be online to receive commands :)
